### ISSUE TITLE
Upgrade to Luxon 2.0 

### ISSUE THREAD

**Issue by ruizmarc** [dstelljes/luxon-angular#23]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently the package is tied to Luxon 1.2.6, but Luxon 2.0 has been released

## Expected behavior

Use luxon 2.X as dependency

## What is the motivation / use case for changing the behavior?

Luxon 2.0 has been rewritten in Typescript bringing a lot of advantages and there are only a few breaking changes

**Comment by dstelljes** [comment]
It doesn’t appear that there are types for 2.0 yet. From the [upgrade guide](https://moment.github.io/luxon/#/upgrading):

> We originally had more ambitious plans for Luxon 2.0: a port to Typescript, an overhaul of error handling, and lots of other changes.

> hopefully someday we'll get back to those more ambitious plans.

The last update to [`@types/luxon`](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/luxon) was for 1.27.0. I’ll update deps and cut a release as soon as types are available.

**Comment by dstelljes** [comment]
Updated in #26, released in 4.0.0.
