### ISSUE TITLE
Can't use recent versions with angular 13

### ISSUE THREAD

**Issue by eLod** [dstelljes/luxon-angular#53]
Maybe i am missing something, but when trying to use 6.0.0 in an Angular 13 app i get the error

```
./node_modules/luxon-angular/fesm2020/luxon-angular.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: Cannot create property 'message' on string '...snip.../node_modules/luxon-angular/fesm2020/luxon-angular.mjs: This application depends upon a library published using Angular version 15.0.2, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.
  10 | }
  11 | DateTimeEarliestPipe.ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "15.0.2", ngImport: i0, type: DateTimeEarliestPipe, deps: [], target: i0.ɵɵFactoryTarget.Pipe });
> 12 | DateTimeEarliestPipe.ɵpipe = i0.ɵɵngDeclarePipe({ minVersion: "14.0.0", version: "15.0.2", ngImport: i0, type: DateTimeEarliestPipe, name: "dateTimeEarliest" });
     |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  13 | i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "15.0.2", ngImport: i0, type: DateTimeEarliestPipe, decorators: [{
  14 |             type: Pipe,
  15 |             args: [{'
```

5.0.0 is the latest version i can use with angular 13.0.3.

**Comment by dstelljes** [comment]
Yeah, it looks like that was caused by the SDK bump in 5.1.0. That was unintentional; the library should follow https://angular.io/guide/releases#actively-supported-versions.

Is there a particular feature you were hoping to use that isn’t available in 5.0.0?

**Comment by eLod** [comment]
yeah, the options support for the pipes (i would use the `dateTimeFromIso`, particularly i need to display datetimes in a given zone), but eventually i want to upgrade angular as well (and meanwhile i can add the pipe myself, i am just using dateTimeFromIso currently), so feel free to ignore or postpone if you prefer.

**Comment by dstelljes** [comment]
Sounds good. I’d rather leave the SDK change in place to avoid creating more confusion; going forward I’ll keep the SDK on the earliest supported LTS. Sorry for the trouble!
